language: node_js
node_js:
- 8
install:
- npm install
- npm update
- npm build
- npm run i18n:src
- npm run i18n:push
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: develop
