language: node_js
node_js:
- 8
install:
- npm install
- npm update
- cd node_modules/scratch-vm && ln -s $(npm root)/google-closure-library ../closure-library --force && npm --production=false install && cd -
- npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: develop
